from .chargement import load_and_check_data
from .data_cleaning import clean_ecommerce_data
from .features_enginering import enrich_ecommerce_data
from .visualisation_ventes import analyser_ventes
from .clustering import (compute_rfm_scores, perform_kmeans_clustering, summarize_clusters)
from .retour_produits import (detecter_produits_problemes_qualite, detecter_produits_les_plus_retournes)